export interface NoteTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  emoji: string;
  bgColor: string;
  accentColor: string;
  content: string;
  checklistItems?: { id: string; text: string; checked: boolean }[];
}

export const NOTE_TEMPLATES: NoteTemplate[] = [

  // ─── Plan Your Life ───────────────────────────────────────────
  {
    id: 'finishing-manifesto',
    title: 'Finishing Manifesto',
    description: 'Follow through with your plans and tasks successfully.',
    category: 'Plan Your Life',
    emoji: '✅',
    bgColor: '#E8F5E9',
    accentColor: '#4CAF50',
    content: '',
    checklistItems: [
      { id: '1', text: 'Fear of failure', checked: false },
      { id: '2', text: 'Lack of confidence', checked: false },
      { id: '3', text: 'Imposter syndrome', checked: false },
      { id: '4', text: 'Laziness', checked: false },
    ],
  },
  {
    id: 'atomic-habits',
    title: 'Atomic Habits Intention',
    description: 'Set your habits and intentions for the day.',
    category: 'Plan Your Life',
    emoji: '⚛️',
    bgColor: '#FFF3E0',
    accentColor: '#FF9800',
    content: `# Atomic Habits Intention\n\nI will [behaviour] at [time] in [location].\n\nExample: I will work on homework at 5pm in Starbucks\n\n## My Intentions:\n1. I will _____ at _____ in _____\n2. I will _____ at _____ in _____\n3. I will _____ at _____ in _____`,
  },
  {
    id: 'daily-planner',
    title: 'Daily Planner',
    description: 'Plan your day for maximum productivity.',
    category: 'Plan Your Life',
    emoji: '📅',
    bgColor: '#E3F2FD',
    accentColor: '#2196F3',
    content: `# Daily Planner\n\n## Morning Routine\n\n## Top 3 Priorities\n1. \n2. \n3. \n\n## Schedule\n- 9:00 AM — \n- 11:00 AM — \n- 2:00 PM — \n- 4:00 PM — \n\n## Evening Review\nWhat went well:\nWhat to improve:`,
  },
  {
    id: 'weekly-goals',
    title: 'Weekly Goals',
    description: 'Set and track your goals for the entire week.',
    category: 'Plan Your Life',
    emoji: '🎯',
    bgColor: '#EDE7F6',
    accentColor: '#673AB7',
    content: `# Weekly Goals\n\nWeek of: ___________\n\n## This Week I Want To:\n1. \n2. \n3. \n\n## Monday\n- [ ] \n\n## Tuesday\n- [ ] \n\n## Wednesday\n- [ ] \n\n## Thursday\n- [ ] \n\n## Friday\n- [ ] \n\n## Weekend\n- [ ] \n\n## End of Week Review\nAccomplishments:\nCarry forward:`,
  },
  {
    id: 'vision-board',
    title: 'Vision Board Notes',
    description: 'Write down your dreams and long-term vision.',
    category: 'Plan Your Life',
    emoji: '🌟',
    bgColor: '#FFFDE7',
    accentColor: '#F9A825',
    content: `# My Vision Board\n\n## 1 Year From Now I Will:\n\n## 5 Years From Now I Will:\n\n## My Dream Life Looks Like:\n\n## Values I Live By:\n1. \n2. \n3. \n\n## My Why:\n\n## Affirmation:\n`,
  },
  {
    id: 'budget-planner',
    title: 'Monthly Budget',
    description: 'Track your income and expenses every month.',
    category: 'Plan Your Life',
    emoji: '💰',
    bgColor: '#E0F2F1',
    accentColor: '#00897B',
    content: `# Monthly Budget\n\nMonth: ___________\n\n## Income\n- Salary: \n- Freelance: \n- Other: \n**Total Income: **\n\n## Fixed Expenses\n- Rent/EMI: \n- Utilities: \n- Subscriptions: \n\n## Variable Expenses\n- Food: \n- Transport: \n- Shopping: \n- Entertainment: \n\n## Savings Goal: \n## Actual Savings: \n\n## Notes:`,
  },

  // ─── Healthy Living ───────────────────────────────────────────
  {
    id: 'anger-log',
    title: 'Anger Log',
    description: 'Record experiences that impact your mood.',
    category: 'Healthy Living',
    emoji: '❤️',
    bgColor: '#FFF8E1',
    accentColor: '#FF5722',
    content: `# Anger Log ❤️ - Date & Time\n\nWhat happened:\n_Describe the incident..._\n\nName of people around you:\n1. Person A\n2. Person B\n3. Person C\n\nWhat emotions did you experience:\n\nWhat triggered you:\n\nHow did you respond:\n\nWhat could you do differently:`,
  },
  {
    id: 'calorie-counter',
    title: 'Calorie Counter',
    description: 'Keep track of your daily calorie intake.',
    category: 'Healthy Living',
    emoji: '🥗',
    bgColor: '#E8F5E9',
    accentColor: '#66BB6A',
    content: `# Daily Calories Intake\n\n| Meals | Food | Calories |\n|-------|------|----------|\n| Breakfast | | |\n| Lunch | | |\n| Tea Break | | |\n| Dinner | | |\n| Snacks | | |\n\n**Total: _____ cal**\n\nGoal: _____ cal`,
  },
  {
    id: 'gratitude-journal',
    title: 'Gratitude Journal',
    description: 'Build a positive mindset with daily gratitude.',
    category: 'Healthy Living',
    emoji: '🙏',
    bgColor: '#F3E5F5',
    accentColor: '#9C27B0',
    content: `# Gratitude Journal\n\nDate: ___________\n\n## 3 Things I'm Grateful For:\n1. \n2. \n3. \n\n## Today's Affirmation:\n\n## One Kind Thing I Did:\n\n## Tomorrow I Look Forward To:`,
  },
  {
    id: 'workout-log',
    title: 'Workout Log',
    description: 'Track your exercise sessions and progress.',
    category: 'Healthy Living',
    emoji: '💪',
    bgColor: '#FCE4EC',
    accentColor: '#E91E63',
    content: `# Workout Log\n\nDate: ___________\nDuration: _____ mins\n\n## Warm Up\n- \n\n## Exercises\n| Exercise | Sets | Reps | Weight |\n|----------|------|------|--------|\n| | | | |\n| | | | |\n| | | | |\n| | | | |\n\n## Cool Down\n- \n\n## How I Felt:\n## Notes:`,
  },
  {
    id: 'sleep-tracker',
    title: 'Sleep Tracker',
    description: 'Monitor your sleep quality and patterns.',
    category: 'Healthy Living',
    emoji: '😴',
    bgColor: '#E8EAF6',
    accentColor: '#3F51B5',
    content: `# Sleep Tracker\n\nDate: ___________\n\nBedtime: \nWake Time: \nTotal Hours: \n\n## Sleep Quality (1–10): \n\n## How I Felt in the Morning:\n\n## What Helped Sleep Better:\n- \n\n## What Disrupted Sleep:\n- \n\n## Tomorrow's Bedtime Goal:`,
  },
  {
    id: 'water-intake',
    title: 'Water Intake',
    description: 'Stay hydrated by tracking your daily water intake.',
    category: 'Healthy Living',
    emoji: '💧',
    bgColor: '#E1F5FE',
    accentColor: '#0288D1',
    content: '',
    checklistItems: [
      { id: '1', text: 'Glass 1 — Morning (250ml)', checked: false },
      { id: '2', text: 'Glass 2 — Mid Morning (250ml)', checked: false },
      { id: '3', text: 'Glass 3 — Before Lunch (250ml)', checked: false },
      { id: '4', text: 'Glass 4 — After Lunch (250ml)', checked: false },
      { id: '5', text: 'Glass 5 — Afternoon (250ml)', checked: false },
      { id: '6', text: 'Glass 6 — Evening (250ml)', checked: false },
      { id: '7', text: 'Glass 7 — Before Dinner (250ml)', checked: false },
      { id: '8', text: 'Glass 8 — Night (250ml)', checked: false },
    ],
  },

  // ─── Love & Relationships ─────────────────────────────────────
  {
    id: 'love-letter',
    title: 'Love Letter',
    description: 'Express your feelings to someone special.',
    category: 'Love & Relationships',
    emoji: '💌',
    bgColor: '#FCE4EC',
    accentColor: '#E91E63',
    content: `# Dear ___________,\n\nDate: ___________\n\nI wanted to tell you that...\n\nWhat I love most about you:\n1. \n2. \n3. \n\nA memory I treasure with you:\n\nHow you make me feel:\n\nWhat I wish for us:\n\nForever yours,\n_____________`,
  },
  {
    id: 'relationship-goals',
    title: 'Relationship Goals',
    description: 'Set meaningful goals with your partner.',
    category: 'Love & Relationships',
    emoji: '💑',
    bgColor: '#FFF0F3',
    accentColor: '#F06292',
    content: `# Our Relationship Goals\n\nNames: _____ & _____\nDate: ___________\n\n## Short Term (3 months)\n1. \n2. \n3. \n\n## Long Term (1 year)\n1. \n2. \n3. \n\n## Things We Want To Do Together:\n- [ ] Travel to \n- [ ] Try \n- [ ] Learn \n\n## Our Strengths as a Couple:\n\n## What We're Working On:\n\n## Our Promise to Each Other:`,
  },
  {
    id: 'date-night-planner',
    title: 'Date Night Planner',
    description: 'Plan the perfect date night for you and your partner.',
    category: 'Love & Relationships',
    emoji: '🌹',
    bgColor: '#FFF3E0',
    accentColor: '#FF7043',
    content: '',
    checklistItems: [
      { id: '1', text: 'Choose a theme or vibe', checked: false },
      { id: '2', text: 'Book restaurant or activity', checked: false },
      { id: '3', text: 'Plan outfit', checked: false },
      { id: '4', text: 'Arrange transport', checked: false },
      { id: '5', text: 'Prepare a surprise element', checked: false },
      { id: '6', text: 'Write a sweet note', checked: false },
    ],
  },
  {
    id: 'self-love-journal',
    title: 'Self Love Journal',
    description: 'Nurture your relationship with yourself daily.',
    category: 'Love & Relationships',
    emoji: '🫶',
    bgColor: '#F8BBD9',
    accentColor: '#AD1457',
    content: `# Self Love Journal\n\nDate: ___________\n\n## Today I Am Proud Of:\n\n## I Forgive Myself For:\n\n## Things I Love About Myself:\n1. \n2. \n3. \n\n## How I'll Take Care of Myself Today:\n\n## Affirmation:\n\n## A Kind Thing I'll Say To Myself:`,
  },

  // ─── Travel ───────────────────────────────────────────────────
  {
    id: 'trip-planner',
    title: 'Trip Planner',
    description: 'Plan every detail of your next adventure.',
    category: 'Travel',
    emoji: '✈️',
    bgColor: '#E3F2FD',
    accentColor: '#1565C0',
    content: `# Trip Planner\n\nDestination: ___________\nDates: _____ to _____\nBudget: ₹/$ _____\n\n## Flights\n- Departure: \n- Return: \n- Booking ref: \n\n## Accommodation\n- Hotel/Airbnb: \n- Address: \n- Check-in: \n- Check-out: \n\n## Day-wise Itinerary\n### Day 1\n- Morning: \n- Afternoon: \n- Evening: \n\n### Day 2\n- Morning: \n- Afternoon: \n- Evening: \n\n## Must Visit:\n- \n\n## Must Eat:\n- \n\n## Packing List:\n- [ ] Passport / ID\n- [ ] Chargers\n- [ ] Clothes\n- [ ] Medicines`,
  },
  {
    id: 'packing-list',
    title: 'Packing Checklist',
    description: 'Never forget anything on your next trip.',
    category: 'Travel',
    emoji: '🧳',
    bgColor: '#E8F5E9',
    accentColor: '#2E7D32',
    content: '',
    checklistItems: [
      { id: '1', text: 'Passport / Aadhar / ID', checked: false },
      { id: '2', text: 'Flight / train tickets', checked: false },
      { id: '3', text: 'Hotel booking confirmation', checked: false },
      { id: '4', text: 'Cash & cards', checked: false },
      { id: '5', text: 'Clothes (per day + 1 extra)', checked: false },
      { id: '6', text: 'Toiletries & medicines', checked: false },
      { id: '7', text: 'Phone charger & power bank', checked: false },
      { id: '8', text: 'Earphones', checked: false },
      { id: '9', text: 'Sunscreen & sunglasses', checked: false },
      { id: '10', text: 'Camera / GoPro', checked: false },
    ],
  },
  {
    id: 'travel-journal',
    title: 'Travel Journal',
    description: 'Capture your memories and experiences while traveling.',
    category: 'Travel',
    emoji: '📖',
    bgColor: '#FFF8E1',
    accentColor: '#F57F17',
    content: `# Travel Journal\n\nLocation: ___________\nDate: ___________\nWeather: ___________\n\n## Today's Highlights:\n\n## Places I Visited:\n1. \n2. \n3. \n\n## Best Food I Had:\n\n## People I Met:\n\n## Something That Surprised Me:\n\n## Something I Learned:\n\n## Rating Today (1–10): \n\n## Tomorrow's Plan:`,
  },
  {
    id: 'road-trip',
    title: 'Road Trip Planner',
    description: 'Plan a fun and safe road trip with your crew.',
    category: 'Travel',
    emoji: '🚗',
    bgColor: '#EFEBE9',
    accentColor: '#6D4C41',
    content: `# Road Trip Planner\n\nFrom: ___________\nTo: ___________\nDate: ___________\nCrew: ___________\n\n## Route\n- Stop 1: \n- Stop 2: \n- Stop 3: \n- Destination: \n\n## Car Checklist\n- [ ] Fuel full\n- [ ] Tyre pressure checked\n- [ ] Spare tyre\n- [ ] First aid kit\n- [ ] Music playlist ready\n\n## Snacks to Pack:\n- \n\n## Budget Split:\nFuel: \nFood: \nAccommodation: \nTotal per person: \n\n## Emergency Contacts:`,
  },
];

export const TEMPLATE_CATEGORIES = [
  'All',
  'Plan Your Life',
  'Healthy Living',
  'Love & Relationships',
  'Travel',
];