import { StyleSheet } from 'react-native';

import {
    Dimensions
} from 'react-native';
const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 48) / 2;

export const globalStyles = StyleSheet.create({
    container: { flex: 1 },
    stickyAdContainer: { width: '100%', alignItems: 'center' },
    gridContainer: { flexDirection: 'row', gap: 10 },
    gridColumn: { flex: 1 },
    header: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: 16, marginTop: 30, paddingBottom: 10,
    },
    headerLeft: { flex: 1 },
    headerTitle: { fontSize: 26, fontWeight: '700' },
    premiumButton: { padding: 2 },
    premiumBadge: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    headerRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    layoutButton: { padding: 4 },
    settingsButton: { padding: 4 },
    notesList: { flex: 1 },
    monthGroup: {
        marginBottom: 8,
    },
    monthHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
        paddingVertical: 10,
        marginBottom: 6,
        borderBottomWidth: 0.5,
    },
    monthLabel: {
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    monthCount: {
        fontSize: 12,
        fontWeight: '500',
    },
    notesListContent: { padding: 12, paddingBottom: 100 },
    emptyContentContainer: { flexGrow: 1 },
    loadingContainer: { paddingVertical: 60, alignItems: 'center' },
    loadingText: { fontSize: 15 },
    emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    emptyTitle: { fontSize: 22, fontWeight: '600', marginTop: 20 },
    emptySubtitle: { fontSize: 15, marginTop: 8, textAlign: 'center', paddingHorizontal: 40 },
    overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 998 },
    fabContainer: {
        position: 'absolute', bottom: 120, right: 40,
        zIndex: 999, alignItems: 'flex-end',
    },
    pillIconBtn: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
    },
    fabOptionWrapper: { position: 'absolute', bottom: 0, right: 0 },
    fabPillButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 12,
        borderRadius: 30,
        gap: 8,
        elevation: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        alignSelf: 'flex-start',
    },
    fabPillText: { color: '#fff', fontSize: 15, fontWeight: '600', flexShrink: 0 },
    addButtonCircle: {
        width: 56, height: 56, borderRadius: 28,
        justifyContent: 'center', alignItems: 'center',
        elevation: 8, shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3, shadowRadius: 8,
    },
    iconPill: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 22,
        borderWidth: 0.5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    pillDivider: {
        width: 0.5,
        height: 20,
    },

    //calendar
    selectedDateBar: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginHorizontal: 16,
        marginBottom: 8,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 0.5,
    },
    selectedDateText: {
        flex: 1,
        fontSize: 13,
        fontWeight: '500',
    },
    todayBtn: {
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    todayBtnText: {
        fontSize: 12,
        fontWeight: '600',
    },

    //coach.tsx

    section: { marginBottom: 28 },
    sectionSubtitle: { fontSize: 13, lineHeight: 18 },

    horizontalList: {
        paddingHorizontal: 10,
        gap: 12,
        paddingBottom: 4,
    },
    card: {
        width: CARD_WIDTH,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08, shadowRadius: 8, elevation: 3,
    },

    filterRow: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        gap: 8,
        alignItems: 'center',
    },
    filterChip: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        alignSelf: 'center',
    },
    filterChipText: {
        fontSize: 13,
        fontWeight: '600',
        includeFontPadding: false,
    },
    scrollContent: {
        paddingTop: 4,
        paddingBottom: 40,
    },
    sectionHeader: {
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: '700',
        marginTop: 8,
        marginBottom: 4,
    },
    cardPreview: {
        height: 160, padding: 12,
        justifyContent: 'flex-start',
    },
    cardPreviewEmoji: { fontSize: 20, marginBottom: 4 },
    cardPreviewTitle: { fontSize: 12, fontWeight: '700', marginBottom: 6 },
    cardPreviewRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 3 },
    cardPreviewCheck: { width: 10, height: 10, borderRadius: 2, borderWidth: 1.5 },
    cardPreviewItem: { fontSize: 9, color: '#555', flex: 1 },
    cardPreviewContent: { fontSize: 9, color: '#666', lineHeight: 13 },
    cardInfo: { padding: 10 },
    cardTitle: { fontSize: 13, fontWeight: '700', marginBottom: 3 },
    cardBadge: { fontSize: 11, color: '#888' },

    modalContainer: { flex: 1 },
    modalBack: { padding: 16, paddingTop: 12 },
    modalPreview: {
        margin: 16, borderRadius: 20,
        padding: 20, minHeight: 200,
    },
    modalPreviewEmoji: { fontSize: 28, marginBottom: 8 },
    modalPreviewTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
    modalPreviewRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
    modalPreviewCheck: { width: 14, height: 14, borderRadius: 3, borderWidth: 1.5 },
    modalPreviewItem: { fontSize: 13, color: '#444' },
    modalPreviewContent: { fontSize: 12, color: '#555', lineHeight: 18 },
    modalBody: { paddingHorizontal: 20 },
    modalTitle: { fontSize: 26, fontWeight: '700', marginBottom: 8 },
    modalDescription: { fontSize: 16, lineHeight: 24, marginBottom: 20 },
    useBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 8, paddingVertical: 16, borderRadius: 30, marginBottom: 24,
    },
    useBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' },
    metaRow: {
        flexDirection: 'row', alignItems: 'center',
        borderWidth: 1, borderRadius: 16, padding: 16, marginBottom: 20,
    },
    metaItem: { flex: 1, alignItems: 'center', gap: 6 },
    metaDivider: { width: 1, height: 40 },
    metaText: { fontSize: 13 },
    coachAvatar: {
        width: 36, height: 36, borderRadius: 18,
        backgroundColor: '#E3F2FD',
        alignItems: 'center', justifyContent: 'center',
    },
    coachAvatarText: { fontSize: 20 },
    freeLabel: { fontSize: 12, fontWeight: '700', letterSpacing: 1.5, marginBottom: 8 },
    modalFullDesc: { fontSize: 15, lineHeight: 24 },
    premiumBtn: { padding: 8 },

    //setting.tsx
    darkContainer: {
        backgroundColor: '#121212',
    },
    darkHeader: {
        borderBottomColor: '#333',
    },
    backButton: {
        padding: 4,
    },
    darkText: {
        color: '#fff',
    },
    placeholder: {
        width: 32,
    },
    content: {
        flex: 1,
        marginLeft: 15,
        marginRight: 15,
        marginBottom: 25,
    },
    settingCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 4,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    darkCard: {
        backgroundColor: '#1e1e1e',
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 12,
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    settingTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1a1a1a',
    },
    settingSubtitle: {
        fontSize: 13,
        color: '#888',
        marginTop: 2,
    },
    darkSubtitle: {
        color: '#999',
    },
    versionText: {
        fontSize: 14,
        color: '#888',
        fontWeight: '500',
    },
    bottomSpacing: {
        height: 40,
    },

    //checklist screen
    keyboardView: { flex: 1 },
    headerButton: { padding: 0, minWidth: 44 },
    saveBtn: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    saveBtnText: { color: '#fff', fontWeight: '700' },
    scrollView: { flex: 1 },
    titleInput: { fontSize: 26, fontWeight: '700', marginBottom: 24, paddingVertical: 6, borderBottomWidth: 2 },
    itemRow: {
        flexDirection: 'row', alignItems: 'center', paddingVertical: 10,
        borderBottomWidth: StyleSheet.hairlineWidth, gap: 8,
    },
    checkbox: { width: 22, height: 22, borderRadius: 5, borderWidth: 2 },
    checkboxFilled: { width: 22, height: 22, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
    itemInput: { flex: 1, fontSize: 16, paddingVertical: 2 },
    addItemBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, gap: 8 },
    addItemText: { fontSize: 16, fontWeight: '500' },
    completedSection: { marginTop: 16 },
    divider: { height: 1, marginBottom: 14 },
    completedLabel: { fontSize: 12, fontWeight: '600', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.6 },
    checkedText: { flex: 1, fontSize: 16, textDecorationLine: 'line-through' },

    //drawing screen
    root: { flex: 1 },
    headerBtn: { padding: 8 },
    headerCenter: { flexDirection: 'row', alignItems: 'center', gap: 2 },
    headerIconBtn: { padding: 8 },
    doneBtn: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },

    canvasWrapper: { overflow: 'hidden' },
    textOverlay: { position: 'absolute', pointerEvents: 'none' },
    stickerOverlay: { position: 'absolute', pointerEvents: 'none' },

    toolbar: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around',
        paddingVertical: 10, paddingHorizontal: 4,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: 'rgba(120,120,128,0.25)',
    },
    toolBtn: {
        flex: 1, alignItems: 'center', justifyContent: 'center',
        paddingVertical: 10, borderRadius: 10,
    },

    colorWheelOuter: {
        width: 30, height: 30, borderRadius: 15,
        borderWidth: 2.5, alignItems: 'center', justifyContent: 'center',
    },
    colorWheelInner: { width: 15, height: 15, borderRadius: 8 },

    plusCircle: {
        width: 30, height: 30, borderRadius: 15,
        borderWidth: 2, alignItems: 'center', justifyContent: 'center',
    },

    floatingPanel: {
        position: 'absolute',
        borderRadius: 16, padding: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.2, shadowRadius: 14, elevation: 14,
    },
    colorPreviewRow: {
        flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14,
    },
    colorPreviewSwatch: {
        width: 44, height: 44, borderRadius: 12,
        borderWidth: 1, borderColor: 'rgba(120,120,128,0.2)',
    },
    colorPreviewInfo: { flex: 1 },
    colorPreviewLabel: { fontSize: 15, fontWeight: '600' },
    colorPreviewSub: { fontSize: 12, marginTop: 2 },

    colorGrid: {
        flexDirection: 'row', flexWrap: 'wrap', gap: 8,
        justifyContent: 'flex-start', marginBottom: 14,
    },
    colorSwatch: {
        width: 34, height: 34, borderRadius: 17,
        alignItems: 'center', justifyContent: 'center',
    },
    colorSwatchSelected: {
        borderWidth: 3, borderColor: '#007AFF',
        shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3, shadowRadius: 4, elevation: 4,
    },

    sliderRow: {
        flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10,
    },
    sliderLabel: { fontSize: 12, fontWeight: '500', width: 50 },
    sliderTrack: { flex: 1, flexDirection: 'row', gap: 4 },
    sliderStep: {
        flex: 1, height: 18, borderRadius: 4,
    },
    sliderStepActive: {
        borderWidth: 2, borderColor: '#007AFF',
        transform: [{ scaleY: 1.3 }],
    },
    sliderValue: { fontSize: 12, fontWeight: '600', width: 32, textAlign: 'right' },
    addMenuItem: {
        flexDirection: 'row', alignItems: 'center',
        paddingHorizontal: 14, paddingVertical: 13, gap: 12, marginBottom: 10,
    },
    addMenuIconWrap: { width: 36, height: 36, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
    addMenuLabel: { fontSize: 16, fontWeight: '500' },
    menuDivider: { height: StyleSheet.hairlineWidth, marginLeft: 62 },

    textModalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
    textModalBox: { padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20 },
    textModalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
    textModalInput: {
        borderWidth: 1.5, borderRadius: 12,
        padding: 12, fontSize: 16, minHeight: 80, marginBottom: 16,
    },
    textModalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12 },
    textModalCancel: { paddingVertical: 10, paddingHorizontal: 16 },
    textModalConfirm: { paddingVertical: 10, paddingHorizontal: 24, borderRadius: 10 },
    popupOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.55)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    popupBox: {
        width: '100%',
        borderRadius: 24,
        padding: 28,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 20,
        elevation: 20,
    },
    popupIconWrap: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: '#FF9F0A22',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    popupTitle: {
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 8,
        textAlign: 'center',
    },
    popupSub: {
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 24,
    },
    popupBtnAd: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 2,
        justifyContent: 'center',
        marginBottom: 12,
    },
    popupBtnAdText: {
        fontSize: 16,
        fontWeight: '600',
    },
    popupBtnPremium: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
        paddingVertical: 14,
        borderRadius: 14,
        justifyContent: 'center',
        marginBottom: 16,
    },
    popupBtnPremiumText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    popupCancel: {
        paddingVertical: 4,
    },
    //languageselection.tsx

    languageheader: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 16,
    },
    iconButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },

    languageheaderTitle: {
        fontSize: 20,
        fontWeight: '700',
        // marginLeft: 10,
        alignItems: 'center',
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'right',
    },
    languagecontent: {
        flex: 1,
    },
    languageList: {
        marginTop: 16,
        marginHorizontal: 16,
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    languageItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 16,
    },
    languageInfo: {
        flex: 1,
    },
    languageName: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    nativeName: {
        fontSize: 13,
    },
    radioOuter: {
        width: 22,
        height: 22,
        borderRadius: 11,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    radioInner: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    languagedivider: {
        height: 1,
        marginHorizontal: 16,
    },

    //note editormodal.tsx

    noteheader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingTop: 50, paddingBottom: 4 },
    noteheaderBtn: { padding: 4, minWidth: 44 },
    notedoneBtn: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    doneTxt: { color: '#fff', fontWeight: '700', fontSize: 14 },
    dateLine: { textAlign: 'center', fontSize: 13, paddingBottom: 8 },
    notescrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
    notetitleInput: { fontSize: 26, fontWeight: '700', lineHeight: 34, marginBottom: 12, padding: 0 },
    contentInput: { fontSize: 17, lineHeight: 26, minHeight: 300, padding: 0, textAlignVertical: 'top' },
    panel: { borderTopWidth: StyleSheet.hairlineWidth, maxHeight: 260 },
    panelInner: { padding: 16 },
    panelTitle: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 12 },
    fontRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 10, borderRadius: 10, borderWidth: 1, marginBottom: 6 },
    //   toolbar: { flexDirection: 'row', alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, paddingBottom: 30, paddingTop: 20, paddingHorizontal: 10 },
    btnLabel: { fontSize: 17, fontWeight: '600', letterSpacing: -0.5 },
    fontBtnLabel: { fontSize: 18, fontWeight: '700', fontStyle: 'italic', letterSpacing: -0.5 },
    premiumDot: { position: 'absolute', top: -4, right: -5, width: 14, height: 14, borderRadius: 7, backgroundColor: '#FF9F0A', alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#fff' },
    imgPreview: { width: '100%', height: 200, borderRadius: 12, borderWidth: 1 },
    imgSaveBtn: { position: 'absolute', top: 8, right: 8, borderRadius: 11, padding: 6, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
    // Checklist panel styles
    clRow: {
        flexDirection: 'row', alignItems: 'center',
        paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, gap: 10,
    },
    clCheckbox: {
        width: 20, height: 20, borderRadius: 4, borderWidth: 2,
    },
    clCheckboxFilled: {
        width: 20, height: 20, borderRadius: 4,
        alignItems: 'center', justifyContent: 'center',
    },
    clInput: { flex: 1, fontSize: 15, paddingVertical: 2 },
    clCheckedText: { flex: 1, fontSize: 15, textDecorationLine: 'line-through' },
    clAddBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, gap: 8 },
    clAddText: { fontSize: 14, fontWeight: '500' },

    // Inline body display
    clSectionHeader: {
        flexDirection: 'row', alignItems: 'center', gap: 6,
        paddingBottom: 8, borderBottomWidth: StyleSheet.hairlineWidth, marginBottom: 4,
    },
    clSectionTitle: { fontSize: 11, fontWeight: '600', letterSpacing: 0.8 },
    clBodyRow: {
        flexDirection: 'row', alignItems: 'center', gap: 10,
        paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth,
    },
    clBodyText: { flex: 1, fontSize: 16 },
    clBodyTextDone: { flex: 1, fontSize: 16, textDecorationLine: 'line-through' },

    // NEW — yeh add/replace karo
    toolbarWrapper: {
        paddingHorizontal: 12,
        paddingBottom: 34,
        paddingTop: 8,
        // backgroundColor: 'transparent',
    },
    toolbarPill: {
        borderRadius: 20,
        borderWidth: 0.5,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    toolbarScroll: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 4,
        paddingVertical: 2,
    },
    toolbarBtn: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
    },
    toolDivider: {
        width: 0.5,
        height: 22,
        marginHorizontal: 2,
    },

    // iOS Sheet styles
    sheetOverlay: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.25)',
        zIndex: 10,
    },
    sheet: {
        position: 'absolute',
        bottom: 0, left: 0, right: 0,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderWidth: 0.5,
        borderBottomWidth: 0,
        maxHeight: '55%',
        zIndex: 11,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 20,
    },
    sheetHandleRow: {
        alignItems: 'center',
        paddingTop: 10,
        paddingBottom: 4,
    },
    sheetHandle: {
        width: 36,
        height: 4,
        borderRadius: 2,
        opacity: 0.4,
    },
    sheetTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderBottomWidth: 0.5,
    },
    sheetTitle: {
        fontSize: 15,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    sheetCloseBtn: { padding: 2 },
    sheetClosePill: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sheetContent: {
        padding: 16,
        paddingBottom: 32,
    },

    //notification screen
    notificationheader: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
        paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12,
    },
    backBtn: { padding: 4 },
    notificationheaderTitle: { fontSize: 20, fontWeight: '700' },
    notificationcontent: { padding: 16, paddingBottom: 60 },
    notificationcard: {
        borderRadius: 16, borderWidth: 0.5,
        padding: 16, marginBottom: 12,
    },
    row: { flexDirection: 'row', alignItems: 'center' },
    iconBox: {
        width: 40, height: 40, borderRadius: 10,
        alignItems: 'center', justifyContent: 'center',
    },
    rowTitle: { fontSize: 16, fontWeight: '600' },
    rowSubtitle: { fontSize: 13, marginTop: 2 },
    infoBox: {
        flexDirection: 'row', alignItems: 'flex-start', gap: 8,
        padding: 12, borderRadius: 12, borderWidth: 1,
    },
    infoText: { flex: 1, fontSize: 13, lineHeight: 19 },
    sectionLabel: {
        fontSize: 11, fontWeight: '700', letterSpacing: 1,
        marginBottom: 10,
    },
    noteRow: {
        flexDirection: 'row', alignItems: 'center',
        padding: 14, borderRadius: 14, borderWidth: 0.5,
        marginBottom: 10,
    },
    noteTitle: { fontSize: 15, fontWeight: '600' },
    noteDate: { fontSize: 12, marginTop: 2 },
    activeBadge: {
        paddingHorizontal: 10, paddingVertical: 4,
        borderRadius: 20,
    },
    activeBadgeText: { fontSize: 11, fontWeight: '600' },
    notificationemptyState: {
        alignItems: 'center', paddingTop: 60, paddingHorizontal: 30,
    },
    notificationemptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16 },
    notificationemptySubtitle: { fontSize: 14, textAlign: 'center', marginTop: 8, lineHeight: 20 },

    //premiumscreen.tsx

    scroll: { paddingBottom: 0 },
    heroSection: { width, height: 280, position: 'relative', marginBottom: 40 },
    heroImage: { width: '100%', height: '100%' },
    closeBtn: { position: 'absolute', top: 48, left: 16, zIndex: 10 },
    // closeBtnCircle: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
    closeBtnCircle: {
        width: 40, height: 40, borderRadius: 50,
        alignItems: 'center', justifyContent: 'center',
    },
    titleOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 20, paddingTop: 40 },
    titleOverlayText: { fontSize: 22, fontWeight: '600', textAlign: 'center', lineHeight: 28, marginTop: 10, paddingBottom: 0, color: '#383838' },
    loadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 16 },
    plansContainer: { gap: 12, marginBottom: 40, paddingHorizontal: 20 },
    planCard: { borderRadius: 16, padding: 16, paddingTop: 20, position: 'relative', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
    badge: { position: 'absolute', top: -12, left: 16, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 10 },
    badgeText: { color: '#FFF', fontSize: 12, fontWeight: '700' },
    planRow: { flexDirection: 'row', alignItems: 'center' },
    radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
    radioDot: { width: 11, height: 11, borderRadius: 6 },
    planInfo: { flex: 1 },
    planLabel: { fontSize: 15, fontWeight: '600' },
    planSub: { fontSize: 12, marginTop: 2 },
    discountBox: { alignItems: 'flex-end' },
    discountPill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
    discountPillText: { color: '#FFF', fontWeight: '800', fontSize: 13 },
    discountTextBox: { alignItems: 'flex-end' },
    discountText: { fontSize: 14, fontWeight: '700' },
    discountLabel: { fontSize: 11, marginTop: 2 },
    subscribeWrap: { marginBottom: 16, paddingHorizontal: 20 },
    subscribeBtn: { borderRadius: 50, paddingVertical: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', shadowColor: '#faab00', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.35, shadowRadius: 14, elevation: 8 },
    subscribeBtnText: { color: '#FFF', fontSize: 18, fontWeight: '800' },
    restoreBtn: { alignItems: 'center', justifyContent: 'center', paddingVertical: 12, marginBottom: 20 },
    restoreText: { fontSize: 14, textDecorationLine: 'underline' },
    footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 12, paddingHorizontal: 20, marginBottom: 12 },
    footerLink: { fontSize: 13, textDecorationLine: 'underline' },
    footerDivider: { width: 1, height: 14, opacity: 0.4 },

    //puchase success
    purchasecontainer: {
        flex: 1,
        backgroundColor: '#E8F7F8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    crownWrap: {
        marginBottom: 40,
    },
    crownOuter: {
        width: 160,
        height: 160,
        borderRadius: 80,
        backgroundColor: 'rgba(250,171,0,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    crownInner: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: 'rgba(250,171,0,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textBlock: {
        alignItems: 'center',
        marginBottom: 60,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 12,
    },
    checkCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#22c55e',
        alignItems: 'center',
        justifyContent: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: '#1A1A1A',
    },
    subtitle: {
        fontSize: 15,
        color: '#666',
        lineHeight: 22,
    },
    btnWrap: {
        position: 'absolute',
        bottom: 36,
        width: width - 40,
    },
    btn: {
        backgroundColor: '#faab00',
        borderRadius: 50,
        paddingVertical: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#faab00',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 14,
        elevation: 8,
    },
    btnText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '800',
    },

    splashcontainer: {
        flex: 1,
        backgroundColor: '#f0ede9',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    bgCircle1: {
        position: 'absolute',
        width: width * 0.9,
        height: width * 0.9,
        borderRadius: width * 0.45,
        backgroundColor: '#fbf2dde0',
        top: -width * 0.2,
        right: -width * 0.2,
    },
    bgCircle2: {
        position: 'absolute',
        width: width * 0.7,
        height: width * 0.7,
        borderRadius: width * 0.35,
        backgroundColor: '#fbf2dde0',
        bottom: -width * 0.1,
        left: -width * 0.2,
    },
    splashcontent: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    logo: {
        width: 100,
        height: 100,
    },
    logoPlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 24,
        backgroundColor: 'rgba(99, 102, 241, 0.2)',
        borderWidth: 1.5,
        borderColor: 'rgba(99, 102, 241, 0.4)',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 20,
    },
    logoIcon: {
        fontSize: 44,
    },
    glowRing: {
        position: 'absolute',
        width: 130,
        height: 130,
        borderRadius: 65,
        borderColor: 'rgba(99, 102, 241, 0.2)',
        backgroundColor: 'transparent',
    },
    appName: {
        fontSize: 38,
        fontWeight: '800',
        color: '#FFFFFF',
        letterSpacing: -0.5,
        marginBottom: 8,
        textShadowColor: 'rgba(99, 102, 241, 0.5)',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 20,
    },
    tagline: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.45)',
        letterSpacing: 0.5,
        fontWeight: '400',
    },

    loaderContainer: {
        position: 'absolute',
        bottom: 60,
        left: 40,
        right: 40,
        alignItems: 'center',
    },
    loaderTrack: {
        width: '100%',
        height: 3,
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 14,
    },
    loaderBar: {
        height: '100%',
        borderRadius: 2,
        backgroundColor: '#e39836',
        shadowColor: '#e39836',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 6,
        elevation: 6,
    },
    loaderText: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.3)',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },

    //theme selection

    themeheader: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 16,
    },

    themeheaderTitle: {
        fontSize: 20,
        // paddingLeft: 10,
        fontWeight: '700',
        alignItems: 'center',
    },
    // saveButton: {
    //     width: 60, height: 35, borderRadius: 5, alignItems: 'center', justifyContent: 'center'
    // },
    themecontent: {
        padding: 16,
    },
    modeLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 16,
    },
    themeGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    themeCard: {
        flex: 1,
        borderRadius: 12,
        padding: 12,
        alignItems: 'center',
        borderWidth: 2,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    previewContainer: {
        width: '100%',
        height: 100,
        marginBottom: 12,
        borderRadius: 8,
        overflow: 'hidden',
    },
    lightPreview: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        padding: 8,
    },
    themesaveButtonText: {
        fontSize: 20,
        paddingTop: 2,
        fontWeight: '600',
        textAlign: 'right',
    },
    darkPreview: {
        flex: 1,
        backgroundColor: '#1a1a1a',
        borderWidth: 1,
        borderColor: '#333',
        borderRadius: 8,
        padding: 8,
    },
    systemPreview: {
        flex: 1,
        flexDirection: 'row',
        borderRadius: 8,
        overflow: 'hidden',
    },
    systemPreviewLeft: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        padding: 6,
        borderTopLeftRadius: 8,
        borderBottomLeftRadius: 8,
    },
    systemPreviewRight: {
        flex: 1,
        backgroundColor: '#1a1a1a',
        borderWidth: 1,
        borderColor: '#333',
        padding: 6,
        borderTopRightRadius: 8,
        borderBottomRightRadius: 8,
    },
    previewHeader: {
        height: 8,
        backgroundColor: '#e0e0e0',
        borderRadius: 2,
        marginBottom: 6,
    },
    previewHeaderDark: {
        height: 8,
        backgroundColor: '#333',
        borderRadius: 2,
        marginBottom: 6,
    },
    previewContent: {
        flex: 1,
        gap: 4,
    },
    previewLine: {
        height: 4,
        backgroundColor: '#e0e0e0',
        borderRadius: 2,
        width: '100%',
    },
    previewLineDark: {
        height: 4,
        backgroundColor: '#333',
        borderRadius: 2,
        width: '100%',
    },
    previewIcon: {
        position: 'absolute',
        bottom: 6,
        right: 6,
    },
    themeLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    radioContainer: {
        marginTop: 4,
    },
    themeradioOuter: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    themeradioInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
});